---
####################################################
####################################################
## Workflow to export and push the digital garden ##
####################################################
####################################################

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
# https://docs.github.com/en/actions/learn-github-actions/introduction-to-github-actions
#

#############################
# Start the job on all push #
#############################
name: Export and push the digital garden

on:
  workflow_dispatch:
  push:
    branches:
      - master

###############
# Set the Job #
###############
jobs:
  export_and_push:
    # Name the Job
    name: Export and push
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - id: step1
        name: Checkout code
        uses: actions/checkout@v2 # see https://github.com/marketplace/actions/checkout
        with:
          token: ${{ secrets.PAT_TOKEN }}
          submodules: true

      #########################
      # Run the export script #
      #########################
      - id: step2
        name: Export the digital garden
        run: |
          ./export.sh
        working-directory: ./scripts
        shell: bash

      ##########################
      # Deploy generated files #
      ##########################
      - id: step3
        name: Commit exported files on submodule
        if: ${{ success() && steps.step2.outputs.exit_code == 0 }}
        uses: EndBug/add-and-commit@v7 # see https://github.com/EndBug/add-and-commit
        with:
          add: --verbose .
          author_name: "josephgarnier"
          author_email: "garnjose@gmail.com"
          branch: master
          cwd: "./export"
          message: Exporting from script
      - id: step4
        name: Commit exported files on main project
        if: ${{ success() }}
        uses: EndBug/add-and-commit@v7 # see https://github.com/EndBug/add-and-commit
        with:
          add: --verbose .
          author_name: "josephgarnier"
          author_email: "garnjose@gmail.com"
          branch: master
          cwd: "."
          message: Exporting from script

