---
#################################################
#################################################
## Export and push the digital garden Workflow ##
#################################################
#################################################

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
# https://docs.github.com/en/actions/learn-github-actions/introduction-to-github-actions
#

#############################
# Start the job on all push #
#############################
name: Export and push the digital garden

on:
  workflow_dispatch:
  push:
    branches:
      - master

###############
# Set the Job #
###############
jobs:
  export_and_push:
    # Name the Job
    name: Export and push
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout code
        uses: actions/checkout@v2

      #########################
      # Run the export script #
      #########################
      - name: Export the digital garden
        run: |
          echo "test"
          ./export.sh
        working-directory: ./scripts
        shell: bash

      ##########################
      # Deploy generated files #
      ##########################
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          add: --verbose ./export/*
          message: Exporting from script
